version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    expose:
      - 3306
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: kiro237/node-skeleton:v2
    depends_on:
      - mysql
    ports:
      - 3000:3000
