apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-skeleton
  labels:
    app: node-skeleton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-skeleton
  template:
    metadata:
      labels:
        app: node-skeleton
    spec:
      containers:
        - name: node-skeleton
          image: kiro237/node-skeleton:v2
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: username
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: db
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: node-skeleton
spec:
  type: NodePort
  selector:
    app: node-skeleton
  ports:
    - protocol: TCP
      port: 3000
---




apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_USER
              value: username
            - name: MYSQL_PASSWORD
              value: password
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
